package application.elements;

public enum Subject {
    AP_EXAM, ART_AND_LIFESKILLS, ENGLISH, GUIDANCE,
    LIFE_SCHOOL, MATHEMATICS, PREFORMING_ARTS, PHYSICAL_EDUCATION,
    SCIENCE, SOCIAL_STUDIES, SPECIAL_EDUCATION, ATHLETICS, N_A;
}
